name: CI and Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'

      - run: npm install

      - run: npm run build
      
      # Hier kannst du weitere Tests oder Schritte hinzufügen, falls nötig
      - run: npm test

      # Führe die Cypress-Tests aus
      - name: Run Cypress Tests
        run: npm run cypress:run
      
      # Wenn die Cypress-Tests erfolgreich sind, deploye auf GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build
          token: ${{ secrets.DEPLOY_TOKEN }}
