name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      # Weitere Schritte für das Bauen deines Projekts...
  
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: npm test
      # Weitere Schritte zum Testen...

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build
          token: ${{ secrets.DEPLOY_TOKEN }}
